Repository Eagle-Strike-7/stelligence-frontend, pull requests merged in 2024-01, with the labels that each got.

#2 #1 [setting] 프로젝트 초기 설정
  .eslintrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .husky/pre-commit
  .nvmrc
  .pnp.cjs
  .pnp.loader.mjs
  .prettierrc
  .vscode/extensions.json
  .vscode/settings.json
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/eslint/lib/api.js
  .yarn/sdks/eslint/lib/unsupported-api.js
  .yarn/sdks/eslint/package.json
  .yarn/sdks/integrations.yml
  .yarn/sdks/prettier/bin/prettier.cjs
  .yarn/sdks/prettier/index.cjs
  .yarn/sdks/prettier/package.json
  .yarn/sdks/typescript/bin/tsc
  .yarn/sdks/typescript/bin/tsserver
  .yarn/sdks/typescript/lib/tsc.js
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/tsserverlibrary.js
  .yarn/sdks/typescript/lib/typescript.js
  .yarn/sdks/typescript/package.json
  .yarnrc.yml
  package.json
  src/app/(home)/page.tsx
  src/app/debateList/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/newStar/page.tsx
  src/app/page.tsx
  src/app/revise/page.tsx
  src/app/voteList/page.tsx
  src/styles/globals.css
  yarn.lock
Labels: ⚙️ setting

#5 #3 [style] 헤더 UI 구현
  src/app/layout.tsx
  src/components/Header/Header.tsx
  src/components/Header/Login.tsx
  src/components/Header/Logo.tsx
  src/components/Header/Navigation.tsx
Labels: 🎀 style

#13 #7 [setting] 공통 컴포넌트 기본 테마 설정
  .pnp.cjs
  src/theme/index.ts
Labels: ⚙️ setting

#14 #12 [style] 공통 컴포넌트 wrapper 컴포넌트 구현
  src/app/(home)/page.tsx
  src/components/Common/Wrapper.tsx
Labels: 🎀 style

#18 #15 [style] 메인페이지 UI 구현
  package.json
  src/app/(home)/page.tsx
  yarn.lock
Labels: ✍️ chore, 🎀 style

#17 #16 [fix] yarn node linker node modules 제거
  .yarnrc.yml
Labels: 🐞 fix

#19 #11 [style] 전역 폰트 설정
  .eslintrc.json
  next.config.js
  public/fonts/PretendardVariable.woff2
  src/components/Header/Logo.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🐞 fix, 🎀 style

#27 #23 [style] 전체 레이아웃 설정 수정
  src/app/(home)/page.tsx
  src/components/Common/Wrapper.tsx
  src/components/Header/Header.tsx
Labels: 🎀 style

#22 #21 [setting] tailwind 색상 설정
  tailwind.config.ts
Labels: ⚙️ setting

#24 #20 [style] 공통 컴포넌트-목록 컴포넌트 UI 구현
  src/app/debateList/page.tsx
  src/components/Common/LikeDislike.tsx
  src/components/Common/ListCard.tsx
  src/constants/dummyData.ts
  src/types/LikeDislikeProps.ts
  src/types/ListCardProps.ts
Labels: 🎀 style

#26 #25 [fix] 공통 컴포넌트 테마 버그 수정
  src/theme/index.ts
Labels: 🐞 fix

#29 #28 [style] 공통 컴포넌트-pagetitle 및 상태 구분 탭 UI 구현
  src/components/Common/PageTitle.tsx
  src/components/Common/StateTab.tsx
  src/types/common/PageTitleProps.ts
  src/types/common/StateTabProps.ts
Labels: 🎀 style

#31 #30 [style] 생성된 댓글 컴포넌트 UI 구현
  src/components/Debate/Comment.tsx
Labels: 🎀 style

#33 #32 [style] 특정 글 수정 요청 페이지 UI 구현
  .pnp.cjs
  package.json
  src/app/[starId]/done/page.tsx
  src/app/[starId]/page.tsx
  src/app/stars/[starId]/page.tsx
  src/app/stars/[starId]/vote/page.tsx
  src/components/Common/LikeDislike.tsx
  src/components/Common/PageTitle.tsx
  src/components/Common/StateTab.tsx
  src/components/Common/Wrapper.tsx
  src/constants/dummyData.ts
  src/types/common/LikeDislikeProps.ts
  src/types/common/PageTitleProps.ts
  src/types/common/StateTabProps.ts
  yarn.lock
Labels: 🐞 fix, ✍️ chore, 🎀 style

#36 #35 [setting] 공통 컴포넌트 chakra 버그 수정
  .pnp.cjs
  src/app/layout.tsx
  src/app/providers.tsx
Labels: 🐞 fix, ⚙️ setting

#40 #35 [fix] customTheme 설정 & 버그 수정
  src/app/layout.tsx
  src/app/providers.tsx
Labels: 🐞 fix

#44 [#41] fix: 메인페이지 수정(가운데 정렬 및 chakra ui 설정 변경)
  src/app/(home)/page.tsx
Labels: 🐞 fix

#43 #4 [style] section 컴포넌트, dummyContentData 생성
  src/components/Common/StarSection.tsx
  src/constants/dummyContentData.ts
Labels: 🎀 style

#42 #6 [style] 로그인 UI 구현
  public/image/googleLogo.png
  public/image/kakaoLogin.png
  public/image/naverLogo.png
  src/app/login/page.tsx
  src/components/Login/GoogleLogin.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/NaverLogin.tsx
Labels: 🎀 style

#48 #9 [style] 특정 글 상세보기 UI 구현
  .pnp.cjs
  src/app/stars/[starId]/Star/StarContent/StarContent.tsx
  src/app/stars/[starId]/Star/StarContributor/StarContributor.tsx
  src/app/stars/[starId]/Star/StarInfo/StarInfo.tsx
  src/app/stars/[starId]/page.tsx
  src/components/Common/StarSection.tsx
  src/constants/dummyContentData.ts
Labels: 🎀 style

#50 #47 [refactor/fix] 팀 규칙 반영 리팩토링 및 오류 해결
  .prettierrc
  src/app/debateList/DebateListCard.tsx
  src/app/layout.tsx
  src/app/stars/[starId]/vote/SpecificVoteListCard.tsx
  src/app/voteList/VoteListCard.tsx
  src/app/voteList/page.tsx
  src/components/Common/PageTitle.tsx
  src/components/Common/StateTab.tsx
  src/components/Header/Header.tsx
  src/components/Header/Login.tsx
  src/components/Header/Logo.tsx
  src/components/Header/Navigation.tsx
Labels: 🐞 fix, 🎀 style, 🛠️ refactor

#51 #38 [feat] 그래프 뷰 d3 기본 설정
  .pnp.cjs
  package.json
  src/app/(home)/GalaxyGraph.tsx
  src/app/(home)/page.tsx
  yarn.lock
Labels: ✨ feat

#52 #6 [style] 로그인 UI 변경
  .pnp.cjs
  src/app/login/page.tsx
  src/components/Login/GoogleLogin.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/NaverLogin.tsx
  src/theme/index.ts
  tailwind.config.ts
Labels: ⚙️ setting, 🎀 style

#54 #53 [feat] 그래프 노드 클릭 시 글 상세페이지로 이동 구현
  src/app/(home)/GalaxyGraph.tsx
  src/app/(home)/page.tsx
Labels: ✨ feat

#59 #58 [setting] eslintrc.json 조건 추가
  .eslintrc.json
Labels: ⚙️ setting

#60 #39 [feat] 소셜로그인 로직 구현
  src/components/Login/GoogleLogin.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/NaverLogin.tsx
Labels: ✨ feat

#64 #62 [feat] 그래프 노드 제목 표시 구현
  src/app/(home)/GalaxyGraph.tsx
  src/app/(home)/page.tsx
Labels: ✨ feat

#61 #57 [style] 그래프 줌 애니메이션 커스텀
  src/app/(home)/GalaxyGraph.tsx
Labels: 🎀 style

#63 #9 [style] 새 글쓰기 ui 구현
  .pnp.cjs
  src/app/newStar/NewStarForm/NewStarForm.tsx
  src/app/newStar/NewStarForm/StarInput.tsx
  src/app/newStar/page.tsx
  src/components/Common/StarSectionInput.tsx
Labels: 🎀 style

#69 [#68] fix: 그래프 뷰 merge 오류 수정 및 줌 애니메이션 확정
  src/app/(home)/GalaxyGraph.tsx
Labels: 🐞 fix

#70 #67 [setting] 폴더 파일 컨벤션 및 각종 버그 수정
  .eslintrc.json
  .gitignore
  .pnp.cjs
  src/app/(home)/components/GalaxyGraph.tsx
  src/app/(home)/page.tsx
  src/app/debateList/components/Comment.tsx
  src/app/debateList/components/DebateListCard.tsx
  src/app/debateList/page.tsx
  src/app/layout.tsx
  src/app/login/components/GoogleLogin.tsx
  src/app/login/components/KakaoLogin.tsx
  src/app/login/components/NaverLogin.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/newStar/components/NewStarForm.tsx
  src/app/newStar/components/StarInput.tsx
  src/app/newStar/page.tsx
  src/app/revise/page.tsx
  src/app/stars/[starId]/components/StarContent.tsx
  src/app/stars/[starId]/components/StarContributor.tsx
  src/app/stars/[starId]/components/StarInfo.tsx
  src/app/stars/[starId]/page.tsx
  src/app/stars/[starId]/vote/components/SpecificVoteListCard.tsx
  src/app/stars/[starId]/vote/page.tsx
  src/app/voteList/components/VoteListCard.tsx
  src/app/voteList/page.tsx
  src/theme/chakra.ts
  yarn.lock
Labels: 🐞 fix, ⚙️ setting, 🛠️ refactor

#72 #56 [feat] 검색 기능 구현
  package.json
  src/app/(home)/components/GalaxyGraph.tsx
  src/app/(home)/page.tsx
  src/styles/graph.module.css
  yarn.lock
Labels: ✨ feat, :chart_with_upwards_trend: enhancement

#75 #74 [style] StarInput 삭제, 상위 계층 태그 검색 드롭다운 ui 구현
  src/app/newStar/components/NewStarForm.tsx
  src/app/newStar/components/StarInput.tsx
Labels: 🎀 style

#79 #77 [chore] react-query 설정
  package.json
  src/app/layout.tsx
  yarn.lock
Labels: ✍️ chore

#78 #71 [style] 마이페이지 UI 구현
  public/image/astronaut.png
  src/app/mypage/components/MyBadge.tsx
  src/app/mypage/page.tsx
  src/components/Common/TitleCard.tsx
Labels: ✨ feat, 🎀 style

#81 #73 [feat] 그래프 뷰 조회 서버 연결
  src/app/(home)/page.tsx
  src/hooks/graph/transformGraphInfo.ts
  src/types/graph/GraphProps.ts
Labels: ✨ feat, :chart_with_upwards_trend: enhancement

#82 #80 [feat] 로그인 페이지 수정
  src/app/login/components/GoogleLogin.tsx
  src/app/login/components/KakaoLogin.tsx
  src/app/login/components/NaverLogin.tsx
  src/app/login/page.tsx
Labels: ✨ feat

#85 #83 [style] 메인페이지 배경 설정 및 UI 세부 수정
  src/app/(home)/page.tsx
  src/components/Header/Header.tsx
  src/components/Header/LeftNav.tsx
  src/components/Header/Login.tsx
  src/components/Header/RightNav.tsx
Labels: 🎀 style

#86 #65 [feat] 글제목, 상위계층태그 연결 기능 구현
  src/app/newStar/components/NewStarForm.tsx
  src/app/newStar/components/NewStarTag.tsx
  src/app/newStar/components/NewStarTitle.tsx
  src/hooks/useDebounce.ts
  src/types/common/ResponseType.ts
  src/types/newStar/newStarProps.ts
Labels: ✨ feat

#88 #87 [style] 서버 연결 이후 그래프 뷰 수정
  src/app/(home)/components/GalaxyGraph.tsx
  src/app/(home)/page.tsx
  src/styles/graph.module.css
  src/types/graph/GraphProps.ts
Labels: ✨ feat, 🎀 style

#90 #76 [feat] 검색 드롭다운 바 구현 및 리팩토링
  .gitignore
  src/app/(home)/components/ErrorComponent.tsx
  src/app/(home)/components/GalaxyGraph.tsx
  src/app/(home)/components/LoadingComponent.tsx
  src/app/(home)/components/SearchDropdown.tsx
  src/app/(home)/components/SearchInput.tsx
  src/app/(home)/page.tsx
  src/components/Header/Header.tsx
  src/hooks/graph/extractIdOnly.ts
  src/hooks/graph/transformGraphInfo.ts
  src/service/graph/getGraphData.ts
  tailwind.config.ts
Labels: ✨ feat, 🎀 style, 🛠️ refactor

#91 [#66] style: 노드 hover시 flow 애니메이션, 같은 그룹 강조 효과 지정
  src/app/(home)/components/GalaxyGraph.tsx
  src/styles/graph.module.css
Labels: 🎀 style

#93 #84 [feat] 마이페이지 기능 구현
  public/image/andromeda.png
  public/image/blackhole.png
  public/image/galaxy.png
  public/image/googleLogo.png
  public/image/guard.png
  public/image/jupiter.png
  public/image/kakaoLogin.png
  public/image/mars.png
  public/image/mercury.png
  public/image/moon.png
  public/image/naverLogo.png
  public/image/neptune.png
  public/image/pluto.png
  public/image/saturn.png
  public/image/sprout.png
  public/image/sun.png
  public/image/uranus.png
  public/image/venus.png
  public/test/dummyBadgeData.json
  public/test/dummyBookmarkData.json
  public/test/dummyUserData.json
  src/app/mypage/page.tsx
  src/service/userService.ts
Labels: ✨ feat, 🛠️ refactor

#95 #94 [style] 마이페이지 UI 수정 및 기능 추가
  src/app/mypage/page.tsx
Labels: ✨ feat, 🎀 style

#100 #94 [fix] 버튼 색상 지정 안되는 버그 수정
  src/app/mypage/page.tsx
Labels: 🐞 fix

#99 #97 [style] 토론 상세페이지 UI 구현(투표 페이지 컴포넌트 제외)
  src/app/debateList/[debateId]/page.tsx
  src/app/debateList/components/Comment.tsx
  src/app/debateList/components/CommentCard.tsx
  src/app/debateList/components/CommentList.tsx
  src/app/debateList/components/CreateComment.tsx
  src/app/debateList/components/PagePreview.tsx
  src/app/debateList/components/RouteToList.tsx
Labels: 🎀 style

#103 #102 [style] 투표 상세페이지 UI 구현
  src/app/revise/[reviseId]/vote/components/Vote.tsx
  src/app/revise/[reviseId]/vote/page.tsx
  src/components/Common/BeforeAfter.tsx
  src/components/Common/TitleInput.tsx
Labels: ✨ feat, 🎀 style

#105 #104 [chore] tiptap 설치
  package.json
  yarn.lock
Labels: ✍️ chore

#108 #107 [dev] 최종 수정 및 1차 main merge
  src/app/debateList/components/CommentCard.tsx
  src/app/debateList/components/CommentList.tsx
  src/app/debateList/components/CreateComment.tsx
  src/app/debateList/components/DebateListCard.tsx
  src/app/debateList/page.tsx
  src/app/login/components/GoogleLogin.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/newStar/components/NewStarForm.tsx
  src/app/newStar/components/NewStarTag.tsx
  src/app/newStar/components/NewStarTitle.tsx
  src/app/revise/[reviseId]/vote/components/Vote.tsx
  src/app/revise/[reviseId]/vote/page.tsx
  src/app/stars/[starId]/voteList/components/SpecificVoteListCard.tsx
  src/app/stars/[starId]/voteList/page.tsx
  src/app/voteList/components/VoteListCard.tsx
  src/components/Common/BeforeAfter.tsx
  src/components/Common/LikeDislike.tsx
  src/components/Common/PageTitle.tsx
  src/components/Common/StarSectionInput.tsx
  src/components/Common/StateTab.tsx
  src/components/Common/TitleInput.tsx
  src/styles/graph.module.css
Labels: 🎀 style, 🛠️ refactor

#111 [#110] deploy: 배포용 .pnp.cjs github에 포함
  .gitignore
  .pnp.cjs
  yarn.lock
Labels: 🌐 deploy

#113 #112 [setting] Jest 환경 설정
  .eslintrc.json
  .pnp.cjs
  jest.config.js
  jest.setup.js
  package.json
  src/tests/index.test.tsx
  tsconfig.json
  yarn.lock
Labels: ⚙️ setting
