Repository Eagle-Strike-7/stelligence-frontend, pull requests merged in 2024-02, with the labels that each got.

#116 #109 [style] 토론 상세페이지 UI 수정
  src/app/debateList/[debateId]/page.tsx
  src/app/debateList/components/CommentCard.tsx
  src/app/debateList/components/CommentList.tsx
  src/app/debateList/components/CreateComment.tsx
  src/app/debateList/components/PagePreview.tsx
  src/app/debateList/components/RouteToList.tsx
  src/app/layout.tsx
Labels: 🎀 style

#120 #89 [feat] 새 글 쓰기 tiptap 기능 구현
  .pnp.cjs
  package.json
  src/app/newStar/components/NewStarForm.tsx
  src/app/revise/components/ReviseStarContent/ReviseStarSectionInput.tsx
  src/app/revise/components/ReviseStarForm.tsx
  src/components/Common/Star/StarSectionInput/FixedMenu.tsx
  src/components/Common/Star/StarSectionInput/StarSectionInput.tsx
  src/components/Common/Star/StarTagInput.tsx
  src/components/Common/StarSectionInput.tsx
  src/styles/globals.css
  src/types/newStar/newStarProps.ts
  yarn.lock
Labels: ✨ feat

#123 #121 [style] 투표 상세페이지 UI 수정
  src/app/revise/[reviseId]/vote/components/ReviseInformation.tsx
  src/app/revise/[reviseId]/vote/components/Vote.tsx
  src/app/revise/[reviseId]/vote/page.tsx
  src/components/Common/BeforeAfter.tsx
  src/components/Common/LabelText.tsx
Labels: 🎀 style

#124 #117 [style] 토론 목록 UI 수정
  src/app/debateList/page.tsx
  src/components/Common/StateTab.tsx
Labels: 🎀 style

#126 #125 [test] 토론 목록 테스트 코드 작성
  src/app/debateList/page.tsx
  src/constants/dummyData.ts
  src/tests/debate/index.test.tsx
  src/tests/index.test.tsx
Labels: 🧪 test

#128 #119 [style] 마이페이지 UI 수정
  public/test/dummyBookmarkData.json
  src/app/mypage/page.tsx
Labels: 🎀 style

#129 #127 [feat] 토론 목록 기능 구현(페이지네이션 제외)
  src/app/debateList/components/DebateListCard.tsx
  src/app/debateList/page.tsx
  src/app/stars/[starId]/voteList/page.tsx
  src/app/voteList/page.tsx
  src/components/Common/ChakraSelect.tsx
  src/components/Common/StateTab.tsx
Labels: 🐞 fix, ✨ feat, 🛠️ refactor

#133 #122 [feat] 로그인 수정 및 로그아웃
  src/app/(home)/page.tsx
  src/app/login/components/GoogleLogin.tsx
  src/app/login/components/KakaoLogin.tsx
  src/app/login/components/NaverLogin.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/components/Header/RightNav.tsx
  src/service/login/axiosClient.ts
  src/service/login/latestLogin.ts
  src/service/login/logout.ts
  src/service/userService.ts
  src/store/user/login.ts
  src/store/user/withdrawal.ts
Labels: ✨ feat

#137 #131 [feat] 토론 상세페이지 서버 연결
  src/app/debateList/[debateId]/components/DebateDetail.tsx
  src/app/debateList/[debateId]/components/DebateSlider.tsx
  src/app/debateList/[debateId]/page.server.tsx
  src/app/debateList/[debateId]/page.tsx
  src/app/debateList/components/CommentCard.tsx
  src/app/debateList/components/CommentList.tsx
  src/types/common/Amendment.ts
Labels: ✍️ chore, ✨ feat, 🛠️ refactor

#138 #130 [feat] 토론 목록 페이지네이션 구현
  src/app/debateList/[debateId]/page.tsx
  src/app/debateList/components/CommentCreate.tsx
  src/app/debateList/components/DebatePrevNextNav.tsx
  src/app/debateList/components/ReturnToDebateList.tsx
  src/app/debateList/page.tsx
Labels: ✨ feat

#140 #132 [test] 토론 상세페이지 테스트 코드 작성(데이터, 댓글)
  src/service/debate/comment.ts
  src/tests/debate/detail/comment.test.tsx
  src/tests/debate/detail/debateAPI.test.tsx
  src/tests/debate/detail/debateState.test.tsx
Labels: 🧪 test

#143 #142 [feat] 글쓰기 사진첨부
  .pnp.cjs
  package.json
  src/app/newStar/components/NewStarForm.tsx
  src/app/revise/components/ReviseStarForm.tsx
  src/components/Common/Star/StarSectionInput/FixedMenu.tsx
  src/components/Common/Star/StarSectionInput/StarSectionInput.tsx
  src/components/Common/Star/StarTagInput.tsx
  src/components/Common/Star/StarTitleInput.tsx
  src/styles/globals.css
  src/styles/starSectionInput.module.css
  src/types/star/NewStarProps.ts
  yarn.lock
Labels: ✨ feat, 🎀 style

#145 #144 [feat] 글쓰기 생성요청
  src/app/newStar/components/NewStarForm.tsx
  src/components/Common/Star/StarTagInput.tsx
Labels: 🐞 fix, ✨ feat

#147 #146 [feat] 글 상세조회 구현
  src/app/stars/[starId]/components/StarAuthors.tsx
  src/app/stars/[starId]/components/StarContent.tsx
  src/app/stars/[starId]/components/StarContributor.tsx
  src/app/stars/[starId]/components/StarInfo.tsx
  src/app/stars/[starId]/page.tsx
  src/styles/starContent.module.css
  src/types/common/ResponseType.ts
  src/types/star/StarProps.ts
Labels: 🐞 fix, ✨ feat, 🎀 style

#152 #139 [feat] 토론 댓글 조회 구현
  src/app/debate-list/[debateId]/components/DebateDetail.tsx
  src/app/debate-list/[debateId]/components/DebateSlider.tsx
  src/app/debate-list/[debateId]/page.server.tsx
  src/app/debate-list/[debateId]/page.tsx
  src/app/debate-list/components/CommentCard.tsx
  src/app/debate-list/components/CommentCreate.tsx
  src/app/debate-list/components/CommentList.tsx
  src/app/debate-list/components/DebateListCard.tsx
  src/app/debate-list/components/DebatePrevNextNav.tsx
  src/app/debate-list/components/ReturnToDebateList.tsx
  src/app/debate-list/page.tsx
  src/app/debateList/components/CommentList.tsx
  src/service/debate/comment.ts
  src/tests/debate/detail/debateAPI.test.tsx
  src/tests/debate/index.test.tsx
  src/types/debate/comment.ts
Labels: ✨ feat

#155 #134 [feat] 투표 목록페이지 기능 구현
  src/app/vote-list/[voteId]/components/ReviseInformation.tsx
  src/app/vote-list/[voteId]/components/Vote.tsx
  src/app/vote-list/[voteId]/page.tsx
  src/app/vote-list/components/VoteListCard.tsx
  src/app/vote-list/page.tsx
  src/app/voteList/components/VoteListCard.tsx
  src/app/voteList/page.tsx
Labels: ✨ feat

#154 #151 [fix] 글 쓰기/조회 데이터 추가 및 수정
  src/app/new-star/components/NewStarForm.tsx
  src/app/new-star/page.tsx
  src/app/revise/components/ReviseStarForm.tsx
  src/app/stars/[starId]/components/StarAuthors.tsx
  src/app/stars/[starId]/components/StarContent.tsx
  src/app/stars/[starId]/components/StarInfo.tsx
  src/app/stars/[starId]/page.tsx
  src/app/stars/[starId]/revise/components/ReviseStarContent/ReviseStarContent.tsx
  src/app/stars/[starId]/revise/components/ReviseStarContent/ReviseStarCreateButton.tsx
  src/app/stars/[starId]/revise/components/ReviseStarContent/ReviseStarSection.tsx
  src/app/stars/[starId]/revise/components/ReviseStarContent/ReviseStarSectionInput.tsx
  src/app/stars/[starId]/revise/components/ReviseStarForm.tsx
  src/app/stars/[starId]/revise/components/ReviseStarInfo/ReviseStarDebate.tsx
  src/app/stars/[starId]/revise/components/ReviseStarInfo/ReviseStarReason.tsx
  src/app/stars/[starId]/revise/page.tsx
  src/components/Common/Button/SubmitButton.tsx
  src/components/Common/Star/StarSectionInput/StarSectionInput.tsx
  src/components/Common/Star/StarTagInput.tsx
  src/components/Common/Star/StarTitleInput.tsx
  src/hooks/common/useDebounce.ts
  src/lib/formatDate.ts
  src/types/star/NewStarProps.ts
  src/types/star/StarProps.ts
Labels: 🐞 fix, ✨ feat, 🛠️ refactor

#158 #153 [feat] 토론 댓글 생성 구현
  src/app/debate-list/[debateId]/page.server.tsx
  src/app/debate-list/[debateId]/page.tsx
  src/app/debate-list/components/CommentCard.tsx
  src/app/debate-list/components/CommentCreate.tsx
  src/app/debate-list/components/CommentList.tsx
  src/lib/debate/scrollToBottom.ts
  src/service/debate/comment.ts
Labels: ✨ feat

#163 #161 [feat] 토론 댓글 수정 구현
  src/app/debate-list/[debateId]/components/CommentCard.tsx
  src/app/debate-list/[debateId]/page.tsx
  src/app/debate-list/components/CommentCard.tsx
  src/app/debate-list/components/CommentList.tsx
  src/service/debate/comment.ts
  src/tests/debate/detail/comment.test.tsx
  src/tests/debate/detail/debateAPI.test.tsx
Labels: ✨ feat

#162 #156 [style] 투표 상세페이지 UI 수정
  src/app/vote-list/[voteId]/components/ReviseInformation.tsx
  src/app/vote-list/[voteId]/page.tsx
  src/components/Common/BeforeAfter.tsx
  src/components/Common/LabelText.tsx
  src/components/Common/PageTitleDescription.tsx
Labels: 🎀 style

#164 #141 [feat] 토론 상세페이지 슬라이더 UI 구현
  .pnp.cjs
  package.json
  src/app/debate-list/[debateId]/components/Carousel/DebateSlider.tsx
  src/app/debate-list/[debateId]/components/Carousel/RouteButton.tsx
  src/app/debate-list/[debateId]/components/Comment/CommentCard.tsx
  src/app/debate-list/[debateId]/components/Comment/CommentCreate.tsx
  src/app/debate-list/[debateId]/components/Comment/CommentList.tsx
  src/app/debate-list/[debateId]/components/DebateDetail.tsx
  src/app/debate-list/[debateId]/components/DebateInformation.tsx
  src/app/debate-list/[debateId]/components/DebateSlider.tsx
  src/app/debate-list/[debateId]/page.tsx
  src/app/debate-list/components/CommentList.tsx
  src/app/debate-list/components/DebatePrevNextNav.tsx
  src/app/debate-list/components/ReturnToDebateList.tsx
  src/app/layout.tsx
  src/components/Common/PageTitleDescription.tsx
  src/components/Header/Header.tsx
  src/components/Header/LeftNav.tsx
  src/components/Header/RightNav.tsx
  src/styles/carousel.module.css
  yarn.lock
Labels: 🐞 fix, ✍️ chore, ✨ feat, 🎀 style

#166 #150 [feat] 수정요청페이지 내용-편집
  src/app/stars/[starId]/components/StarContent.tsx
  src/app/stars/[starId]/components/StarInfo.tsx
  src/app/stars/[starId]/page.tsx
  src/styles/StarSectionShow.module.css
  src/types/common/ResponseType.ts
  src/types/star/ReviseStarProps.ts
  src/types/star/StarProps.ts
Labels: ✨ feat, 🎀 style

#170 #167 [style] 전체 디자인 수정 토론 상세페이지에 반영
  src/app/(home)/page.tsx
  src/app/debate-list/[debateId]/components/Carousel/DebateSlider.tsx
  src/app/debate-list/[debateId]/components/Carousel/RouteButton.tsx
  src/app/debate-list/[debateId]/components/Comment/CommentCard.tsx
  src/app/debate-list/[debateId]/components/Comment/CommentCreate.tsx
  src/app/debate-list/[debateId]/components/Comment/CommentList.tsx
  src/app/debate-list/[debateId]/components/DebateDetail.tsx
  src/app/debate-list/[debateId]/components/DebateInformation.tsx
  src/app/debate-list/[debateId]/page.tsx
  src/app/debate-list/components/ReturnToDebateList.tsx
  src/app/layout.tsx
  src/components/Common/LabelText.tsx
  src/components/Common/PageTitleDescription.tsx
  src/components/Header/Header.tsx
  src/styles/carousel.module.css
  src/theme/chakra.ts
  tailwind.config.ts
Labels: 🐞 fix, 🎀 style

#168 #135 [feat] 투표 상세페이지 데이터 연결 구현
  src/app/vote-list/[voteId]/components/ReviseContent.tsx
  src/app/vote-list/[voteId]/components/ReviseInformation.tsx
  src/app/vote-list/[voteId]/components/Vote.tsx
  src/app/vote-list/[voteId]/page.tsx
  src/app/vote-list/components/VoteListCard.tsx
  src/components/Common/BeforeAfter.tsx
  src/components/Common/LabelText.tsx
  src/lib/calculateRemainTime.ts
  src/service/vote/voteService.ts
  src/styles/starContent.module.css
Labels: ✨ feat

#174 #172 [feat] 토론 종료 시 토론 상세페이지 화면 구현
  src/app/debate-list/[debateId]/components/Carousel/DebateSlider.tsx
  src/app/debate-list/[debateId]/components/Comment/CommentCard.tsx
  src/app/debate-list/[debateId]/components/Comment/CommentCreate.tsx
  src/app/debate-list/[debateId]/components/DebateDetail.tsx
  src/app/debate-list/[debateId]/components/DebateInformation.tsx
  src/app/debate-list/[debateId]/components/MiddleTitle.tsx
  src/app/debate-list/[debateId]/components/NewReviseRequest.tsx
  src/app/debate-list/[debateId]/page.server.tsx
  src/app/debate-list/[debateId]/page.tsx
  src/styles/carousel.module.css
  src/theme/chakra.ts
  tailwind.config.ts
Labels: 🐞 fix, ✨ feat, 🎀 style

#173 #169 [feat] 로그인 상태 전역으로 관리
  src/app/(home)/page.tsx
  src/app/login/components/GoogleLogin.tsx
  src/app/login/components/KakaoLogin.tsx
  src/app/login/components/NaverLogin.tsx
  src/app/mypage/page.tsx
  src/components/Header/RightNav.tsx
  src/components/Login/LoginInterceptor.tsx
  src/hooks/common/useRequireLogin.ts
  src/service/login/axiosClient.ts
  src/service/login/loginState.ts
  src/service/userService.ts
  src/store/user/login.ts
Labels: 🐞 fix, ✨ feat

#176 #175 [feat] 특정 글 히스토리 페이지 UI 구현
  .pnp.cjs
  package.json
  src/app/stars/[starId]/history-list/HistoryTimeline.tsx
  src/app/stars/[starId]/history-list/page.tsx
  src/components/Common/PageTitle.tsx
  src/theme/mui.ts
  yarn.lock
Labels: ✨ feat, 🎀 style

#177 #150 [feat] 수정요청페이지 내용 편집, 추가, 삭제 구현
  src/app/new-star/components/NewStarForm.tsx
  src/app/stars/[starId]/components/StarAuthors.tsx
  src/app/stars/[starId]/components/StarContent.tsx
  src/app/stars/[starId]/components/StarInfo.tsx
  src/app/stars/[starId]/revise/components/CreateButton.tsx
  src/app/stars/[starId]/revise/components/ReviseStarContent/ReviseStarContent.tsx
  src/app/stars/[starId]/revise/components/ReviseStarContent/ReviseStarCreateButton.tsx
  src/app/stars/[starId]/revise/components/ReviseStarContent/ReviseStarSection.tsx
  src/app/stars/[starId]/revise/components/ReviseStarContent/ReviseStarSectionInput.tsx
  src/app/stars/[starId]/revise/components/ReviseStarForm.tsx
  src/app/stars/[starId]/revise/components/ReviseStarInfo/ReviseStarDebate.tsx
  src/app/stars/[starId]/revise/components/ReviseStarInfo/ReviseStarReason.tsx
  src/app/stars/[starId]/revise/components/ReviseStarReason.tsx
  src/app/stars/[starId]/revise/components/ReviseStarSection.tsx
  src/app/stars/[starId]/revise/components/ReviseStarSectionInput.tsx
  src/app/stars/[starId]/revise/components/ReviseStarSectionShow.tsx
  src/app/stars/[starId]/revise/components/ReviseStarSectionTitle.tsx
  src/components/Common/Button/OutlineButton.tsx
  src/components/Common/Star/StarContentInput/FixedMenu.tsx
  src/components/Common/Star/StarContentInput/StarContentInput.tsx
  src/components/Common/Star/StarSectionShow.tsx
  src/components/Common/Star/StarTagInput.tsx
  src/components/Common/Star/StarTitleInput.tsx
  src/styles/StarSectionShow.module.css
  src/styles/globals.css
  src/styles/starContent.module.css
  src/styles/starSectionInput.module.css
Labels: 🐞 fix, ✨ feat, 🎀 style

#184 #165 [enhance] 검색 debouncing 구현
  src/app/(home)/components/Search/SearchDropdown.tsx
  src/app/(home)/components/Search/SearchInput.tsx
  src/app/(home)/page.tsx
Labels: 🛠️ refactor, :chart_with_upwards_trend: enhancement

#186 #185 [style] 토론 목록 페이지 다크모드 UI 수정
  src/app/debate-list/components/DebateListCard.tsx
  src/app/debate-list/page.tsx
  src/components/Common/ChakraSelect.tsx
  src/components/Common/StateTab.tsx
  src/theme/chakra.ts
  src/theme/mui.ts
Labels: 🎀 style

#183 #171 [feat] 마지막 로그인 수단 보여주기
  src/app/login/page.tsx
  src/service/login/latestLogin.ts
  src/styles/login.module.css
Labels: ✨ feat

#191 #190 [style] 그래프 노드 간 글씨 겹침, 그래프 엉킴 현상, 글씨 크기 수정
  src/app/(home)/components/GalaxyGraph.tsx
Labels: 🎀 style

#188 #157 [feat] 투표 상세페이지 기능 구현
  src/app/vote-list/[voteId]/components/ReviseInformation.tsx
  src/app/vote-list/[voteId]/components/Vote.tsx
  src/app/vote-list/[voteId]/page.tsx
  src/components/Common/PageTitleDescription.tsx
  src/service/vote/voteService.ts
Labels: ✨ feat, 🎀 style

#199 #178 [feat] 마이페이지 상세 기능 구현
  public/test/dummyBookmarkData.json
  src/app/mypage/components/MyBadge.tsx
  src/app/mypage/page.tsx
  src/service/userService.ts
  src/types/common/ResponseType.ts
Labels: ✨ feat

#193 #192 [feat] 토론 종료 후 수정 요청 보내기 기능 구현
  src/app/debate-list/[debateId]/components/NewReviseRequest.tsx
  src/app/debate-list/[debateId]/page.tsx
Labels: ✨ feat

#197 #196 [feat] 히스토리 편집 버튼 연결
  src/app/new-star/components/NewStarForm.tsx
  src/app/stars/[starId]/components/StarInfo.tsx
  src/app/stars/[starId]/components/StarStatusButton.tsx
  src/app/stars/[starId]/page.tsx
  src/types/star/StarProps.ts
Labels: ✨ feat, 🎀 style

#202 #201 [fix] 검색 입력 값 없을 때 검색 요청 안보내도록 수정
  src/app/(home)/page.tsx
Labels: 🐞 fix

#200 #187 [feat] 토론 내 다른 댓글 태그 기능 구현
  src/app/debate-list/[debateId]/components/Comment/CommentCard.tsx
  src/app/debate-list/[debateId]/components/Comment/CommentCreate.tsx
  src/app/debate-list/[debateId]/components/Comment/CommentDropdownMenu.tsx
  src/app/debate-list/[debateId]/components/Comment/CommentList.tsx
  src/app/debate-list/[debateId]/page.tsx
  src/lib/debate/renderContentWithTags.tsx
Labels: ✨ feat, 🎀 style, 🛠️ refactor

#203 #136 [style] 투표 선택에 따라 색상 변경
  src/app/vote-list/[voteId]/components/Vote.tsx
  src/service/vote/voteService.ts
Labels: ✨ feat, 🎀 style

#205 #204 [style] 버튼, 글씨크기 수정
  src/app/new-star/components/NewStarForm.tsx
  src/app/stars/[starId]/components/StarAuthors.tsx
  src/app/stars/[starId]/components/StarInfo.tsx
  src/app/stars/[starId]/components/StarStatusButton.tsx
  src/app/stars/[starId]/revise/components/CreateButton.tsx
  src/app/stars/[starId]/revise/components/ReviseStarReason.tsx
  src/app/stars/[starId]/revise/components/ReviseStarSectionShow.tsx
  src/components/Common/Button/SubmitButton.tsx
  src/styles/globals.css
  src/types/common/ResponseType.ts
Labels: 🎀 style

#209 #208 [feat] 히스토리 페이지 서버 연결 및 상세페이지로 이동 구현
  src/app/stars/[starId]/history-list/HistoryTimeline.tsx
  src/app/stars/[starId]/history-list/page.tsx
  src/service/history/getDocumentMaxVesrion.ts
Labels: ✨ feat

#212 #210 [fix] 토론 상세페이지 조회 api 수정 반영, 토론 제목/상위계층태그 변경 사항 수정사항에 추가 렌더링
  src/app/debate-list/[debateId]/components/Carousel/DebateSlider.tsx
  src/app/debate-list/[debateId]/components/DebateDetail.tsx
  src/app/debate-list/[debateId]/components/DebateInformation.tsx
  src/app/debate-list/[debateId]/components/NewReviseRequest.tsx
  src/app/debate-list/[debateId]/page.server.tsx
  src/app/debate-list/[debateId]/page.tsx
  src/lib/debate/transTitleAndTagChanged.ts
  src/types/common/Amendment.ts
Labels: 🐞 fix, ✨ feat, 🛠️ refactor

#214 #179 [feat] 북마크 생성 삭제 구현
  src/app/mypage/page.tsx
  src/app/stars/[starId]/components/StarInfo.tsx
  src/service/userService.ts
Labels: ✨ feat

#222 #221 [feat] 신고 기능 구현
  src/app/debate-list/[debateId]/components/Comment/CommentCard.tsx
  src/app/stars/[starId]/components/StarInfo.tsx
  src/components/Common/ReportModal.tsx
Labels: ✨ feat

#225 #224 [style] 그래프 노드 색 수정
  src/app/(home)/components/GalaxyGraph.tsx
Labels: 🎀 style

#226 #223 [feat] 은하수 여행 가이드 페이지 생성
  src/app/(home)/page.tsx
  src/app/info/components/InfoButton.tsx
  src/app/info/components/InfoMenu.tsx
  src/app/info/page.tsx
  src/app/layout.tsx
Labels: ✨ feat

#233 #229 [refactor] 토론 상세페이지 컴포넌트 재구조화 및 폴더 구조 정리
  src/app/debate-list/[debateId]/components/BackToDebateListButton.tsx
  src/app/debate-list/[debateId]/components/Carousel/DebateSlider.tsx
  src/app/debate-list/[debateId]/components/Comment/CommentCard.tsx
  src/app/debate-list/[debateId]/components/Comments/CommentCard.tsx
  src/app/debate-list/[debateId]/components/Comments/CommentsHeader.tsx
  src/app/debate-list/[debateId]/components/Comments/CommentsSection.tsx
  src/app/debate-list/[debateId]/components/Comments/CreateComment/CommentDisplay.tsx
  src/app/debate-list/[debateId]/components/Comments/CreateComment/CommentDropdownMenu.tsx
  src/app/debate-list/[debateId]/components/Comments/CreateComment/CreateComment.tsx
  src/app/debate-list/[debateId]/components/Comments/CreateComment/EditCommentForm.tsx
  src/app/debate-list/[debateId]/components/DebateDetail/DebateDetail.tsx
  src/app/debate-list/[debateId]/components/DebateDetail/DebateInfo/DebateInformation.tsx
  src/app/debate-list/[debateId]/components/DebateDetail/DebateSlider/DebateSlider.tsx
  src/app/debate-list/[debateId]/components/DebateDetail/DebateSlider/RouteButton.tsx
  src/app/debate-list/[debateId]/components/NewReviseRequestButton.tsx
  src/app/debate-list/[debateId]/page.tsx
  src/app/debate-list/page.tsx
  src/app/info/page.tsx
  src/app/stars/[starId]/components/StarInfo.tsx
  src/app/stars/[starId]/history-list/page.tsx
  src/app/stars/[starId]/revise/components/ReviseStarForm.tsx
  src/app/stars/[starId]/voteList/page.tsx
  src/app/vote-list/[voteId]/page.tsx
  src/app/vote-list/page.tsx
  src/components/Common/Title/MiddleTitle.tsx
  src/components/Common/Title/PageTitle.tsx
  src/components/Common/Title/PageTitleDescription.tsx
Labels: 🛠️ refactor

#231 #219 [feat] 북마크 단건조회 삭제 기능 구현
  src/app/mypage/page.tsx
  src/app/stars/[starId]/components/StarInfo.tsx
  src/service/userService.ts
Labels: ✨ feat

#235 #232 [feat] 로그인 상태 관리 및 에러 처리
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/components/Header/RightNav.tsx
  src/components/Login/LoginInterceptor.tsx
  src/hooks/common/useRequireLogin.ts
  src/store/user/login.ts
Labels: ✨ feat

#236 #182 [style] 투표 마이페이지 디자인 수정
  src/app/mypage/components/MyBadge.tsx
  src/app/mypage/page.tsx
  src/app/vote-list/[voteId]/components/ReviseInformation.tsx
  src/app/vote-list/[voteId]/page.tsx
  src/app/vote-list/components/VoteListCard.tsx
  src/app/vote-list/page.tsx
  src/components/Common/BeforeAfter.tsx
  src/components/Common/LabelText.tsx
  src/components/Common/Star/StarContentInput/FixedMenu.tsx
  src/components/Common/TitleCard.tsx
  src/components/Common/Wrapper.tsx
  src/styles/starContent.module.css
Labels: 🎀 style

#238 #234 [feat] 토론 수정 요청 버튼 권한 및 상태에 따른 조건부 렌더링 구현
  src/app/debate-list/[debateId]/components/DebateDetail/DebateDetail.tsx
  src/app/debate-list/[debateId]/components/NewReviseRequestButton.tsx
  src/app/debate-list/[debateId]/page.server.tsx
  src/app/debate-list/[debateId]/page.tsx
  src/service/debate/reviseAuth.ts
Labels: ✨ feat, 🛠️ refactor

#249 #244 [fix] 댓글 수정 권한에 따른 버튼 클릭 가능 여부 처리
  src/app/debate-list/[debateId]/components/Comments/CommentCard.tsx
  src/app/debate-list/[debateId]/components/Comments/CommentsSection.tsx
  src/app/debate-list/[debateId]/components/Comments/CreateComment/CommentDisplay.tsx
  src/app/debate-list/[debateId]/components/Comments/CreateComment/CreateComment.tsx
  src/app/debate-list/[debateId]/page.tsx
Labels: 🐞 fix

#250 #246 [fix] 토론 목록페이지 버그 수정 시간 마진 정렬
  src/app/debate-list/components/DebateListCard.tsx
  src/app/debate-list/page.tsx
Labels: 🐞 fix

#252 #248 [feat] 특정 글 수정요청 목록 구현
  src/app/stars/[starId]/revised-list/page.tsx
  src/service/revise/reviseService.ts
  src/service/vote/voteService.ts
  src/types/common/ResponseType.ts
Labels: ✨ feat

#253 #237 [fix] 투표 목록에서 클릭 시 투표 상세페이지로 이동하게 변경
  src/app/vote-list/components/VoteListCard.tsx
Labels: 🐞 fix

#251 #198 [feat] 수정요청 / revision, 상위계층태그, 편집버튼
  src/app/stars/[starId]/components/StarInfo.tsx
  src/app/stars/[starId]/components/StarStatusButton.tsx
  src/app/stars/[starId]/page.tsx
  src/app/stars/[starId]/revise/components/ReviseStarForm.tsx
  src/components/Common/Star/StarTagInput.tsx
  src/components/Common/Title/PageTitleDescription.tsx
  src/types/star/StarProps.ts
Labels: 🐞 fix, ✨ feat

#254 #239 [fix] 토론 댓글 정렬 적용 안됨 버그 수정
  src/app/debate-list/[debateId]/components/Comments/CommentsHeader.tsx
  src/app/debate-list/[debateId]/components/Comments/CommentsSection.tsx
  src/app/debate-list/[debateId]/components/Comments/CreateComment/CreateComment.tsx
  src/app/debate-list/[debateId]/page.tsx
Labels: 🐞 fix, ✨ feat

#243 #207 [feat] 글쓰기 언급링크 기능
  .pnp.cjs
  package.json
  src/components/Common/Star/StarContentInput/MentionLink.ts
  src/components/Common/Star/StarContentInput/StarContentInput.tsx
  src/components/Common/Star/StarTagInput.tsx
  src/styles/globals.css
  yarn.lock
Labels: ✨ feat

#258 #257 [fix] 투표 목록 버그 및 디자인 수정
  src/app/stars/[starId]/revised-list/page.tsx
  src/app/vote-list/components/VoteListCard.tsx
  src/app/vote-list/page.tsx
  src/components/Common/LikeDislike.tsx
  src/components/Common/NoList.tsx
  src/theme/chakra.ts
  tailwind.config.ts
Labels: 🐞 fix, 🎀 style

#265 #242 [feat] 수정요청 추가한 섹션의 추가, 수정, 삭제
  .pnp.cjs
  package.json
  src/app/stars/[starId]/revise/components/ReviseStarForm.tsx
  src/app/stars/[starId]/revise/components/ReviseStarSection.tsx
  src/lib/revise/revise.ts
  src/styles/globals.css
  yarn.lock
Labels: ✨ feat

#262 #256 [fix] 한 번 검색 시 추가 검색 안되는 버그 수정
  src/app/(home)/components/GalaxyGraph.tsx
  src/app/(home)/components/Search/SearchDropdown.tsx
  src/app/(home)/components/Search/SearchInput.tsx
  src/app/(home)/page.tsx
  src/hooks/graph/extractIdOnly.ts
  src/service/search/getSearchResult.ts
Labels: 🐞 fix, 🛠️ refactor

#272 #271 [style] 전체 UI 수정
  src/app/debate-list/page.tsx
  src/app/info/components/InfoButton.tsx
  src/app/stars/[starId]/components/StarAuthors.tsx
  src/app/stars/[starId]/components/StarInfo.tsx
  src/app/stars/[starId]/components/StarStatusButton.tsx
  src/app/stars/[starId]/revise/components/CreateButton.tsx
  src/app/stars/[starId]/revise/components/ReviseStarReason.tsx
  src/app/stars/[starId]/revise/components/ReviseStarSectionShow.tsx
  src/app/vote-list/[voteId]/page.tsx
  src/app/vote-list/page.tsx
  src/components/Common/Button/SubmitButton.tsx
  src/components/Common/Star/StarTagInput.tsx
  src/components/Common/Star/StarTitleInput.tsx
  src/components/Common/StateTab.tsx
  src/components/Common/Title/PageTitleDescription.tsx
  src/components/Common/TitleInput.tsx
  src/components/Common/Wrapper.tsx
  src/components/Header/Notification.tsx
  src/styles/starContent.module.css
Labels: 🎀 style

#264 #255 [feat] 토론 댓글 신고 기능 성공실패 알림 구현
  src/app/debate-list/[debateId]/components/Comments/CommentCard.tsx
  src/app/stars/[starId]/components/StarInfo.tsx
  src/components/Common/ReportModal.tsx
  src/service/debate/comment.ts
Labels: ✨ feat

#273 #269 [fix] 로그인 버그 및 디자인 수정
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/stars/[starId]/components/StarStatusButton.tsx
  src/components/Header/RightNav.tsx
  src/components/Login/LoginInterceptor.tsx
Labels: 🐞 fix

#275 #274 [style] 마이페이지 버그 및 디자인 수정
  src/app/mypage/page.tsx
Labels: 🐞 fix, 🎀 style

#268 #259 [fix] 투표 상세페이지 버그 및 디자인 수정
  src/app/vote-list/[voteId]/components/ReviseContent.tsx
  src/app/vote-list/[voteId]/components/ReviseInformation.tsx
  src/app/vote-list/[voteId]/components/Vote.tsx
  src/app/vote-list/[voteId]/components/VoteProgressBar.tsx
  src/app/vote-list/[voteId]/page.tsx
  src/components/Common/BeforeAfter.tsx
  src/components/ReviseDescription.tsx
  src/service/vote/voteService.ts
Labels: 🐞 fix, 🎀 style

#284 #281 [fix] use client 추가
  src/app/stars/[starId]/revise/page.tsx
Labels: 🐞 fix

#286 #285 refactor: 은하수 여행가이드 내용 수정
  src/app/info/page.tsx
Labels: 🛠️ refactor

#289 #242 [feat] 수정요청 추가 추가
  src/app/stars/[starId]/revise/components/ReviseStarForm.tsx
  src/app/stars/[starId]/revise/components/ReviseStarSection.tsx
  src/app/stars/[starId]/revise/components/ReviseStarSectionInput.tsx
Labels: 🐞 fix

#291 #288 [fix] 수정요청 페이지에서 새로고침 로그아웃 버그 수정
  next.config.js
  src/app/new-star/page.tsx
  src/app/stars/[starId]/revise/page.tsx
  src/components/Header/RightNav.tsx
  src/hooks/common/useRequireLogin.tsx
  src/store/user/login.ts
Labels: 🐞 fix

#293 #292 [fix] 수정요청 delete 시 null 오류 수정
  src/app/vote-list/[voteId]/components/ReviseContent.tsx
  src/components/Common/BeforeAfter.tsx
Labels: 🐞 fix

#294 #276 [style] 알림 버그 및 디자인 수정
  src/components/Header/Header.tsx
  src/components/Header/Notification.tsx
  src/components/Header/RightNav.tsx
  src/store/notification/countNotification.ts
Labels: ✨ feat, 🎀 style

#297 #279 [fix] 토론 상세페이지 댓글 작성 관련 버그 수정 및 추가기능 구현
  src/app/debate-list/[debateId]/components/Comments/CommentCard.tsx
  src/app/debate-list/[debateId]/components/Comments/CommentsSection.tsx
  src/app/debate-list/[debateId]/components/Comments/CreateComment/CommentDisplay.tsx
  src/app/debate-list/[debateId]/components/Comments/CreateComment/CommentDropdownMenu.tsx
  src/app/debate-list/[debateId]/components/Comments/CreateComment/CreateComment.tsx
  src/app/debate-list/[debateId]/components/Comments/CreateComment/EditCommentForm.tsx
  src/app/debate-list/[debateId]/page.tsx
  src/lib/debate/renderContentWithTags.tsx
Labels: 🐞 fix, 🛠️ refactor

#299 [#287] feat: favicon 설정
  public/favicon.ico
Labels: 🌐 deploy

#302 #263 [fix] 목록 개수 0개 예외 처리
  src/app/debate-list/[debateId]/components/Comments/CommentsSection.tsx
  src/app/debate-list/[debateId]/page.tsx
  src/app/debate-list/page.tsx
Labels: 🐞 fix

#300 #290 [fix] 글쓰기 상세보기 수정 버그
  src/app/stars/[starId]/components/StarStatusButton.tsx
  src/app/stars/[starId]/revise/components/ReviseStarForm.tsx
  src/app/stars/[starId]/revise/components/ReviseStarSection.tsx
  src/components/Common/Star/StarTagInput.tsx
  src/components/Common/Title/PageTitleDescription.tsx
  src/lib/revise/revise.ts
Labels: 🐞 fix

#308 #307 [fix] 토론 수정 요청 쿼리로 debateId 전달
  src/app/debate-list/[debateId]/components/NewReviseRequestButton.tsx
  src/app/debate-list/[debateId]/page.tsx
Labels: 🐞 fix

#312 #295 [style] 헤더 반응형
  src/components/Header/DebateButton.tsx
  src/components/Header/Header.tsx
  src/components/Header/LeftNav.tsx
  src/components/Header/NewStarButton.tsx
  src/components/Header/RightNav.tsx
  src/components/Header/VoteButton.tsx
  tailwind.config.ts
Labels: 🎀 style

#309 #305 수정 요청 시 앞 문단 추가, 문단 삭제 시 취소선 구현
  src/app/debate-list/[debateId]/components/DebateDetail/DebateSlider/DebateSlider.tsx
  src/app/vote-list/[voteId]/components/ReviseContent.tsx
  src/components/Common/BeforeAfter.tsx
  src/components/Header/Notification.tsx
  src/components/ReviseDescription.tsx
  src/styles/starContent.module.css
Labels: 🐞 fix

#321 #320 신고 ui 다크모드 적용 및 기타 항목 추가
  src/components/Common/ReportModal.tsx
Labels: 🎀 style

#317 #315 [fix] 안읽은 알림 표시 안뜨는 오류 수정
  src/components/Header/Notification.tsx
  src/components/Header/RightNav.tsx
  src/styles/scrollbar.module.css
Labels: 🐞 fix, 🎀 style

#319 #318 [fix] 마지막 로그인 표시 안되는 버그 수정
  src/app/login/page.tsx
  src/components/Header/RightNav.tsx
Labels: 🐞 fix

#323 #290 [fix] 글쓰기 상세보기 수정 버그
  src/app/new-star/components/NewStarForm.tsx
  src/app/stars/[starId]/components/StarAuthors.tsx
  src/app/stars/[starId]/components/StarContent.tsx
  src/app/stars/[starId]/revise/components/ReviseStarSectionInput.tsx
  src/components/Common/Button/SubmitButton.tsx
  src/components/Common/Star/StarContentInput/FixedMenu.tsx
  src/components/Common/Star/StarContentInput/StarContentInput.tsx
  src/components/Common/Star/StarTagInput.tsx
  src/components/Common/Star/StarTitleInput.tsx
  src/lib/handleKeyDown.ts
  src/lib/revise/revise.ts
  src/styles/globals.css
  src/styles/starSectionInput.module.css
Labels: 🐞 fix, ✨ feat

#326 #290 [feat] 작성팁 추가, Placeholder 추가
  src/app/new-star/components/NewStarForm.tsx
  src/components/Common/Star/StarContentInput/StarContentInput.tsx
  src/styles/globals.css
Labels: ✨ feat

#327 #290 [feat] toast 추가
  src/app/new-star/components/NewStarForm.tsx
  src/app/stars/[starId]/revise/components/ReviseStarForm.tsx
  src/app/stars/[starId]/revise/components/ReviseStarSection.tsx
Labels: ✨ feat

#329 #328 [fix] 그래프 뷰 UI 수정
  src/app/(home)/components/GalaxyGraph.tsx
  src/app/(home)/page.tsx
Labels: 🐞 fix
